name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Tested with dotnet
      run: dotnet test advent2018.sln --configuration Release
